# -*- coding: utf-8 -*-
"""PROBLEM 1 : Pandas : Pipe and Pivot Table.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lm1AL1qmKIpoPtCk-H1OlEfxUYaMBuEc
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()

import io

# read and print the titanic dataset

df = pd.read_csv(io.BytesIO(uploaded['titanic.csv']))
df.head()

# Using method 1

df.describe()

# using method 2: 

df.info()

df.sort_values("Pclass").head()

# sellecting column by name: 
  
  df[['Name', 'Pclass']].head()

# Finding ratio: by PClass and Sex


df2=df.groupby(['Pclass'])['Sex'].value_counts('M')
df2=df2.to_frame()*100
df2

