# -*- coding: utf-8 -*-
"""PROBLEM 5. Reproducing Bernoulli Visualization in Seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f6UcdFgyDtVzaPsuFD9vCcbdwAUVdPV0
"""

from google.colab import files
import pandas as pd
import seaborn as sns

uploaded = files.upload()

# loading the data

import io
pickle_data = pickle.load(io.BytesIO(uploaded['pandas_c.pickle']))
pickle_data

