# -*- coding: utf-8 -*-
"""PROBLEM 3. PANDAS OPERATIONS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NvqBeSlDxOKmihC4A2Bxq_zy-b4kfKFu
"""

import pandas as pd
import numpy as np

bardata = pd.DataFrame(np.random.randint(3,10,size=(300,4)),columns=['a', 'b', 'c', 'd'])
bardata.head()

sum_data = bardata.sum(axis=1)
sum_data

min_data = bardata.min(axis=1)
min_data

