# -*- coding: utf-8 -*-
"""PROBLEM 2 : Time Series in BUSINESS Context.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Vgx67TE-1YdQ_Af-DJcworQ7WboJeLq
"""

import pandas as pd
import numpy as np

# Create a DatetimeIndex that contains each business day of 2018

df = pd.bdate_range(start='1/1/2018', end='31/12/2018', freq='B' )
df

# column of random numbers “normalized_losses”

normalized_losses = pd.DataFrame(np.random.randint(0,260,size=(15, 1)))
normalized_losses.head()

